apiVersion: skaffold/v2beta10
kind: Config
# 쿠버네티스 배포 설정
deploy:
  kubectl:
    manifests:
      - ./xinfra/kubernetes/*
    defaultNamespace: devel
# 도커 이미지 빌드 관련 설정
build:
  local:
    push: true
  # googleCloudBuild:
  #   projectId: kubernetes-315817
  artifacts:
    - image: dangtong76/getmem
      context: getmem
      docker:
        dockerfile: Dockerfile
    - image: dangtong76/nodecheck
      context: nodecheck
      docker:
        dockerfile: Dockerfile
    - image: dangtong76/sayservice
      context: sayservice
      docker:
        dockerfile: Dockerfile
    - image: dangtong76/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      # 소스 싱크 관련 설정
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
